---
name: Build CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: deployment
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --name=mongodb
    env:
      MONGODB_URL: mongodb://localhost:27017/acebook_test
      # INSTANCE_IP_ADDRESS: {{ vars.INSTANCE_IP_ADDRESS }}
      # SSH_PRIVATE_KEY: {{ vars.SSH_PRIVATE_KEY }}
    steps:
      - name: Check variables
        run: |
          echo "My SSH key is ${{ vars.SSH_PRIVATE_KEY }}"
          echo ""My SSH key is ${{ vars.INSTANCE_IP_ADDRESS }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint and unit tests
        run: |
          npm run lint
          npm run test:unit
      - name: Run integration tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js
          start: npm run start:ci
      - name: Deploy
        run: bash ./scripts/deploy-to-instance.sh
